### ISSUE TITLE
changing display and maximized windows

### ISSUE THREAD

**Issue by pclouds** [pekdon/pekwm#103]
I'm using my laptop with smaller screen dimension, then I switch to an external display with larger dimension and turn off laptop screen. The maximized windows are unchanged, which do not cover full screen anymore, but they are still in maximized state.

A fix should be simple, I suppose. Probably just something to do with xrandr events then we can remaximize or do other things we need

**Comment by pekdon** [comment]
Thanks for the report AND fix @pclouds
