### ISSUE TITLE
Off-by-one workspace numbers in placement autoproperties

### ISSUE THREAD

**Issue by FrnchFrgg** [pekdon/pekwm#105]
Latest commit has a regression where workspaces numbers seem 0-based instead of 1-based when a window is automatically placed. Windows that used to be auto-placed to workspace 2 now go to 3, etc. When moving windows with actions (aka menus) there is no such off-by-one, so I can put back the windows where they belong manually.

Last known good state was a11768ba0a7ce AFAIR (I didn't bisect yet, and did not see anything that jumped at my face when looking but I do not know where autoproperties happen so may have not looked correctly).

**Comment by pclouds** [comment]
I found the bad commit and proposed the fix in #106, could you help check? I don't use autoprops much...
