### ISSUE TITLE
Last closed windows still exist on panel

### ISSUE THREAD

**Issue by mamans86** [pekdon/pekwm#110]
dear pekwm dev,
I'm using pekwm 0.2.0 on Debian Stretch with tint2 panel, if the last application window is closed, this window is still remain exist on tint2 taskbar but it's inactive (can't be raised because it has actually closed).

this is not happen when i use openbox as window manager. 

is there any config adjustment or fix for this issue ?

thanks in advance

**Comment by mamans86** [comment]
I'm using the default configuration of pekwm 0.2.0 and I'm compiling from source on Debian Stretch

**Comment by pekdon** [comment]
Ok, I'll have a go with the Tint 2 version available on Stretch and see if I can reproduce it then.

Happens with all applications I presume?
