### ISSUE TITLE
Pekwm won't start properly when the locale is set to Turkish

### ISSUE THREAD

**Issue by memetg** [pekdon/pekwm#116]
I've been facing this issue for years but I was too lazy to report. This has been tested on several systems on virtualbox (including arch, opensuse, ubuntu) and on my main system, which is Debian Bullseye (but the issue was there on previous versions of Debian). I've tested it on several locales to see if it's an issue for other languages and have seen that the bug occurs only when the locale is set to Turkish and Azerbaijani.

When the locale is set to Turkish, 
1. The window manager will not respond to mouse clicks; right click will do nothing, so, you will not be able to start any programs. However, the mouse cursor will move.
2. the autostart file in ./pekwm/start will not function, the panels will not start automatically no matter which one you choose (before you ask, the start file is not the problem because the mouse issue is there with a fresh install of pekwm with default configuration). 
As a result, the only way to exit pekwm is to restart the display manager. 

The issue is non-existent if I install the system in English or if I select English when I log in.

Here is the content of my .xsession-errors file when pekwm starts: 

```
 *** WARNING: empty theme directory name, using default.
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@609:
	No such template @Border
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @EmptyDecor
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @Border
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @BaseDecor
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @BaseButtons
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @BaseDecor
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @BorderOnly
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @EmptyDecor
 *WARNING* void CfgParser::parseEntryFinishTemplate(std::string&)@0x261:
	No such template @BorderOnly
 *** WARNING: no title section in decor: Default
 *** WARNING: no title section in decor: Menu
 *** WARNING: no title section in decor: Titlebarless
 *** WARNING: no title section in decor: Statuswindow
 *** WARNING: no title section in decor: WorkspaceIndicator
 *WARNING* bool Theme::load(const string&)@0x3e3:
	Theme doesn't contain any DEFAULT decor.
 *WARNING* void Theme::PDecorData::checkTextures()@0x1aa:
	DEFAULT missing tab texture state FOCUSED
 *WARNING* void Theme::PDecorData::checkTextures()@0x1aa:
	DEFAULT missing tab texture state UNFOCUSED
 *WARNING* void Theme::PDecorData::checkTextures()@0x1aa:
	DEFAULT missing tab texture state FOCUSEDSELECTED
 *WARNING* void Theme::PDecorData::checkTextures()@0x1aa:
	DEFAULT missing tab texture state UNFOCUSEDSELECTED
 *WARNING* void Theme::PDecorData::checkTextures()@0x1b0:
	DEFAULT missing main texture state FOCUSED
 *WARNING* void Theme::PDecorData::checkTextures()@0x1b4:
	DEFAULT missing tab texture state FOCUSED
 *WARNING* void Theme::PDecorData::checkTextures()@0x1b0:
	DEFAULT missing main texture state UNFOCUSED
 *WARNING* void Theme::PDecorData::checkTextures()@0x1b4:
	DEFAULT missing tab texture state UNFOCUSED
 *WARNING* void Theme::PDecorData::checkFonts()@0x1c1:
	DEFAULT missing font state FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture TOPLEFT FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture TOPRIGHT FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture BOTTOMLEFT FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture BOTTOMRIGHT FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture TOP FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture LEFT FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture RIGHT FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture BOTTOM FOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture TOPLEFT UNFOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture TOPRIGHT UNFOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture BOTTOMLEFT UNFOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture BOTTOMRIGHT UNFOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture TOP UNFOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture LEFT UNFOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture RIGHT UNFOCUSED
 *WARNING* void Theme::PDecorData::checkBorder()@0x1cd:
	DEFAULT missing border texture BOTTOM UNFOCUSED
 *WARNING* void Theme::PDecorData::checkColors()@0x1dd:
	DEFAULT missing font color state FOCUSED
 *WARNING* void Theme::PDecorData::checkColors()@0x1dd:
	DEFAULT missing font color state UNFOCUSED
 *WARNING* void Theme::PDecorData::checkColors()@0x1dd:
	DEFAULT missing font color state FOCUSEDSELECTED
 *WARNING* void Theme::PDecorData::checkColors()@0x1dd:
	DEFAULT missing font color state UNFOCUSEDSELECTED
 *WARNING* bool Theme::load(const string&)@0x3f2:
	Missing "CMDDIALOG" section!
 *WARNING* bool Theme::load(const string&)@0x3f6:
	Missing "WORKSPACEINDICATOR" section!
```

**Comment by pekdon** [comment]
Interesting. Starting with a few follow up questions:

- pekwm version used?
- username (is it ASCII only?)

If you have not tried with 0.2.0/0.2.1 please do, use of iconv was removed so could very well affect this.

If you have the possibility to log into some other WM with those locales set and provide the output from the command **locale** that could also be helpful.

**Comment by memetg** [comment]
The pekwm version on my current system (Debian Bullseye) is 0.1.18-1, the bug had been there in former versions of pekwm, too. 
I've just installed pekwm 0.2.1 on Arch to see if the bug is still there; on 0.2.1 pekwm immediately crashes and returns to the display manager. If I choose English, again, there is no problem. I'm not very familiar with Arch, I checked .xsession-errors file to post the content in it, but the file was empty, and I couldn't find anything on google on how to see the session errors.

My username is memet on all of the systems, no non-ascii characters. 

I have used openbox, jwm, icewm, fluxbox and blackbox so far, no problems with any of them. 

the output of locale command on my Debian system, I'm currently on JWM:

```
LANG=tr_TR.UTF-8
LANGUAGE=
LC_CTYPE="tr_TR.UTF-8"
LC_NUMERIC=tr_TR.UTF-8
LC_TIME=tr_TR.UTF-8
LC_COLLATE="tr_TR.UTF-8"
LC_MONETARY=tr_TR.UTF-8
LC_MESSAGES="tr_TR.UTF-8"
LC_PAPER=tr_TR.UTF-8
LC_NAME=tr_TR.UTF-8
LC_ADDRESS=tr_TR.UTF-8
LC_TELEPHONE=tr_TR.UTF-8
LC_MEASUREMENT=tr_TR.UTF-8
LC_IDENTIFICATION=tr_TR.UTF-8
LC_ALL=
```
The output on Openbox Arch is exactly the same minus the second line (`LANGUAGE=`).

**Comment by pekdon** [comment]
Thanks for the information. Standard UTF-8 locale, should be nothing special with that (but seems to be given it does not work.

See /doc/development.md for details on how to provide information about a crash, if it is indeed a crash that happens with 0.2.1.

I'll try to see if I can reproduce when I get back in front of a computer in a couple of days or so.

**Comment by memetg** [comment]
Well, I'm not very tech savvy (and this is partly why I was being lazy about reporting a bug). I've read development.md and tried to figure out how to run pekwm with the mentioned parameters, I suppose stopping the display manager starting x server manually with the wm name and the parameters in the .xinitrc file is the way to go, but I must first learn how to start X manually in a proper way (I get some x related errors right now).

So I'll have to wait till I've some more free time, I suppose.

**Comment by pekdon** [comment]
No worries, should experience the same issue so will get back in a couple of days! :)

**Comment by pclouds** [comment]
I got interested (and it's been a few days! kidding) so I looked a bit into it. The crash is because of nullptr on "this" but that's probably secondary issue because of failing to load config files. Will add more when I find something new. Interestingly I tried another locale but it didn't crash. Something special about Turkish locale.

BTW. The way pekwm launches pekwm_wm is really inconvient for debugging with gdb, is there anyway I can just launch pekwm_wm directly?

**Comment by pclouds** [comment]
Apparently strcasecmp does not work as expected (or as _expected_ to Turks but not to us?) This simple program demonstrates this

```
#include <string.h>
#include <stdio.h>
#include <locale.h>

int main(int ac, const char** av)
{
	setlocale (LC_ALL, "");
	printf("%d\n", strcasecmp("FILES", "Files"));
	return 0;
}
```

The problem is also highlighted here. pekwm code wants case-insensitive (and use strcasecmp for that) but because strcasecmp fails, pekwm can't even find "files" section to read more files...

With this finding I could at least start pekwm with

    LANG=tr_TR.UTF-8 LC_CTYPE=C pekwm

which forces strcasecmp to work right. But this is probably not what we want.

**Comment by pekdon** [comment]
@pclouds nice find. I guess what we want is to do our own ASCII (no UTF8 names used in the config files) strcasecmp and use that instead. Still, very much interesting that ASCII characters behave differently in Turkish locale.

As for debugging, I'll add a standalone flag to pekwm_wm so the pekwm process can be skipped.

**Comment by pclouds** [comment]
OK two options to move forward:

* avoid strcasecmp, ffmpeg [goes this way](https://gitea.bjx.cloud/public/ffmpeg/commit/96949dafcca87f65902bd77a0bc56007d9cead70)
* set LC_CTYPE but you have to be careful, see how [git handles it](https://github.com/git/git/blob/master/gettext.c#L81)

**Comment by pekdon** [comment]
And @pclouds, I'm adding the string compare and the standalone pekwm flag. Halfway there, but need to go but am off from work now during christmas so should be in there shortly.

**Comment by pclouds** [comment]
I actually forgot it was christmas (not a big thing where I live), take your time off :) even if memetg wants to run pekwm now the LC_CTYPE workaround would suffice.

**Comment by memetg** [comment]
>  Still, very much interesting that ASCII characters behave differently in Turkish locale.

> The problem is also highlighted here. pekwm code wants case-insensitive (and use strcasecmp for that) but because strcasecmp fails, pekwm can't even find "files" section to read more files...

I am trying to understand (noob alert): strcasecmp looks for the string FILES and expects to find "files", do I understand correctly? If that's the case, that would be the expected behaviour. Just in case this might give you an insight, the problem is, there are two pairs of letters in Turkish corresponding to the English letter "I,i" and those are "I,ı" and "İ,i". The lowercase of the letter "I" is "ı" (both lowercase and uppercase are dotless) in Turkish and the uppercase of the letter "i" is "İ" (both uppercase and lowercase are dotted) in Turkish. So looking for the string "FILES" will result in searching for "fıles", and looking for the string "files" will result in searching for "FİLES". 

I had reported a similar bug for an android application, all he did was [to keep the encoding in English](https://github.com/Haptic-Apps/Slide/issues/2449#issuecomment-335652993) in order to work the issue around.

**Comment by memetg** [comment]
> I actually forgot it was christmas (not a big thing where I live), take your time off :) even if memetg wants to run Pekwm now the LC_CTYPE workaround would suffice.

I tried it and can confirm that pekwm (0.1.18-1, Debian Bullseye) starts, but this time there are problems with the menus: the menu item names are not complete, they stop at the first non-English characters. For example all I can see is "G" instead of "Görüntüleyiciler" because the menu apparently cannot show the letter "ö". A few examples: 
Pencere Yöneticileri -> Pencere Y
Ağ -> A
Düzenleyiciler -> D
Erişilebilirlik -> Eri
Görüntüleyiciler -> G

The strange part is that when I start Pekwm in English (from LXDM), the Turkish Debian menus are still there and the non-English characters are rendered correctly.

**Comment by pclouds** [comment]
OK this part about menus, I'll leave it to pekdon because it probably involves fonts or encoding in x11 which I'm not really familiar about. Good to know about those Turkish pairs though.
