### ISSUE TITLE
What actions aren't bound in default config?

### ISSUE THREAD

**Issue by psprint** [pekdon/pekwm#118]
I'm looking forward for configuring pekwm more by including some unused by default actions. What are such actions? Any examples or list of them? Where to find them?

**Comment by pekdon** [comment]
There's no list of unbound actions, no plan on adding one either however if you read the docs you get a full list of the available actions. See [doc/actions.md](/pekdon/pekwm/blob/master/doc/actions.md) for details.

The default configuration, at least for keys, is quite extensive so you might want to strip your keys and mouse and start re-adding the things you want to get a better understanding of the configuration.
