### ISSUE TITLE
Menu config Exec takes '&' as an argument

### ISSUE THREAD

**Issue by krejvl** [pekdon/pekwm#124]
I've already updated my pekwm from 0.1.17 to 0.2.1 in Gentoo (I work on a new ebuild for Gentoo). I've just found that using '&' to run apps listed in a menu config on background (as the documentation recommends) causes those apps to take '&' as an argument. So

'Exec google-chrome-stable &'

runs Chrome with new tab with '%26' URL, keepass try to open a '${HOME}/&' database file and so on. 

I'm not sure if this is a bug or feature - if feature, the documentation needs update I guess.

**Comment by pekdon** [comment]
This was noted in the NEWS.md file as:

```
Exec no longer use sh -c to run commands which will cause incompatabilites depending on /bin/sh configuration, if shell variables have been used or the command ends with &. ShellExec has been added implementing the legacy behaviour.
```

But of course should be updated in the documentation.

**Comment by krejvl** [comment]
Thank you, I'll notice this in the ebuild.

**Comment by pclouds** [comment]
> I work on a new ebuild for Gentoo

Are you the new maintainer for pekwm? You may want to have a look at https://bugs.gentoo.org/821184 (and close it if it's no longer valid)

**Comment by krejvl** [comment]
No, not yet. I've prepared new ebuild and informed the proxy maintainers team. They told me to just do pull request and they'll do the rest then. I'm ready to do so and waiting for a response to few questions on the new ebuild before pull request. I was not aware of the  https://bugs.gentoo.org/821184 and I'm sure it will be closed as soon as we finish this up.
