### ISSUE TITLE
compile for 32-bit

### ISSUE THREAD

**Issue by IAW9927** [pekdon/pekwm#127]
I am compiling on 64-bit and I get 64-bit, NOT a 32-bit like my test system expects.

**Comment by pekdon** [comment]
Really need more information here, but producing a 64bit binary on a 64bit is expected on most platforms.

Are you using the builtin configure script or cmake (preferred way of building)?
What OS/Distro/Tools etc are you on and using?

Anyway, typically you can try doing CXXFLAGS="-m32" or similar to produce a 32 bit binary.

**Comment by IAW9927** [comment]
build error: pekwm.cc: In function ‘int main(int, char**)’:
<command-line>: error: expected primary-expression before ‘/’ token
../mk/config.h:8:20: note: in expansion of macro ‘PREFIX’
    8 | #define SYSCONFDIR PREFIX "/etc/pekwm"
      |                    ^~~~~~
pekwm.cc:134:27: note: in expansion of macro ‘SYSCONFDIR’
  134 |  setenv("PEKWM_ETC_PATH", SYSCONFDIR, 1);
      |                           ^~~~~~~~~~
<command-line>: error: ‘usr’ was not declared in this scope
../mk/config.h:8:20: note: in expansion of macro ‘PREFIX’
    8 | #define SYSCONFDIR PREFIX "/etc/pekwm"
      |                    ^~~~~~
pekwm.cc:134:27: note: in expansion of macro ‘SYSCONFDIR’
  134 |  setenv("PEKWM_ETC_PATH", SYSCONFDIR, 1);
      |                           ^~~~~~~~~~
<command-line>: error: ‘local’ was not declared in this scope
../mk/config.h:8:20: note: in expansion of macro ‘PREFIX’
    8 | #define SYSCONFDIR PREFIX "/etc/pekwm"
      |                    ^~~~~~
pekwm.cc:134:27: note: in expansion of macro ‘SYSCONFDIR’
  134 |  setenv("PEKWM_ETC_PATH", SYSCONFDIR, 1);
      |                           ^~~~~~~~~~
<command-line>: error: expected primary-expression before ‘/’ token
../mk/config.h:7:17: note: in expansion of macro ‘PREFIX’
    7 | #define DATADIR PREFIX "/share"
      |                 ^~~~~~
pekwm.cc:135:30: note: in expansion of macro ‘DATADIR’
  135 |  setenv("PEKWM_SCRIPT_PATH", DATADIR "/pekwm/scripts", 1);
      |                              ^~~~~~~
<command-line>: error: expected primary-expression before ‘/’ token
../mk/config.h:7:17: note: in expansion of macro ‘PREFIX’
    7 | #define DATADIR PREFIX "/share"
      |                 ^~~~~~
pekwm.cc:136:29: note: in expansion of macro ‘DATADIR’
  136 |  setenv("PEKWM_THEME_PATH", DATADIR "/pekwm/themes", 1);
      |                             ^~~~~~~
make[1]: *** [Makefile:82: pekwm.o] Error 1
make[1]: Leaving directory '/home/asher/flwm/fltk_projects/pekwm/pekwm/src'
make: *** [Makefile:6: all] Error 2

**Comment by pekdon** [comment]
So, still wondering what OS you're on.

Also, try building using CMake if the simple Makefiles work for you.

**Comment by IAW9927** [comment]
Debian 11 (amd64)

**Comment by IAW9927** [comment]
I am using "make".

**Comment by IAW9927** [comment]
Ok, fixed the error with a patch.
1c1
< #define PREFIX "/usr/local"
---
>
