### ISSUE TITLE
Feature request: action related to SetGeometry which accepts percentages

### ISSUE THREAD

**Issue by okraits** [pekdon/pekwm#13]
The following would be handy:

An action like the SetGeometry action which would accept percentages for width and height and then calculate the resulting window size out of the size of the current monitor.

An example could be:

`SetGeometryRel 50 50`

This would resize a window on a monitor with a resolution of 1920x1200 to 960x600.

**Comment by pekdon** [comment]
Started work on it in geometry-percent, feel free to try it out @okraits. Needs more testing/tests. Works with the existing actions taking a geometry, just add % after the value.

**Comment by okraits** [comment]
@pekdon Wow, that was quick! I just wanted to document the idea and didn't expect that you would work on this any time soon. Thank you! I'm using this branch now, the SetGeometry action works as expected. I have to do more testing though, of course.

BTW, I'm happy that you started to work on pekwm again. Maybe see you some time on IRC? :grin:

**Comment by okraits** [comment]
I noticed one thing: `SetGeometry 50%x100%` doesn't honor the vertical space a panel demands (tint2 here) - the resized window covers the panel, as opposed to vertically maximized windows.

**Comment by pekdon** [comment]
For relative positions the strut has never been taken into account. Not sure if the same action should be used, a new action should be introduced or just another option to SetGeometry that says include strut in calculations.

SetGeometry supports an extra parameter which specifies the head it is to be applied on, there is currently no way of saying the current head (head the cursor is on)

Guess SetGeometry 50%x100% active include-strut or something like that could do the trick

**Comment by okraits** [comment]
I should have read the documentation for SetGeometry more thoroughly.

Currently the head option accepts an integer, with -1 for the whole screen or the desired head number. I think introducing another special number like -2 for the active head is not very intuitive.

What about turning the head option into a string like you already suggested? Then we could use values like active, whole-screen or the RandR output names to specify a specific head.

A new option like include-strut would be pretty useful as well.

**Comment by pekdon** [comment]
Merged to master, hopefully works as expected.

**Comment by okraits** [comment]
@pekdon Thank you very much!

**Comment by pclouds** [comment]
Should this be documented in doc/actions.md? I was searching for some other things that led me to this, and it isn't very clear there that percentages are supported.

**Comment by okraits** [comment]
> Should this be documented in doc/actions.md? I was searching for some other things that led me to this, and it isn't very clear there that percentages are supported.

Yes!

As an example, here is what I'm using:

`SetGeometry 50%x50% current HonourStrut`

_current_ means that the geometry is relative to the current head.
_HonourStrut_ means that panels are taken into account.
