### ISSUE TITLE
Zombie spawn

### ISSUE THREAD

**Issue by biopsin** [pekdon/pekwm#14]
Hi, lovely seeing pekwm is moving forward.
Any particular reason I get multiple zombie prosesses with this action in my mouse config,

```
ScreenEdge {
	Left {
		EnterMoving = "Any Any" { Actions = "Exec wmctrl -r :ACTIVE: -e 0,10,10,1905,2140" }
	}
	Right {
		EnterMoving = "Any Any" { Actions = "Exec wmctrl -r :ACTIVE: -e 0,1925,10,1905,2140" }
	}
}
```

**Comment by pekdon** [comment]
Does it happen all the time, or do you do something specific to make the zombies appear?

**Comment by biopsin** [comment]
All the time, triggered immediately draging window to either side.

Also tested substitute with internal commands instead
`    Entry = "Toggle Vertical" { Actions = "Toggle Maximized False True" }`
where this does not trigger these zombie processes, but
it's very sensitive and one has to try some times to actually acomplish the task + no window horizontal scaling .
My humble opinion; those mouse EnterMoving actions need a limit logic per action too.

**Comment by pekdon** [comment]
Sorry for the late reply, I have an untested fix for my theory on what is going on in the branch zombie-14 if you want to try it out before I get a local reproduction going.

**Comment by biopsin** [comment]
Splendid, I'll should manage testing it this weekend..

**Comment by pekdon** [comment]
Ok, thanks for the feedback! Back to the drawing board and I'll try to get a local reproduction going.

**Comment by pekdon** [comment]
I've reworked the joining of children a bit more and added trace logging on master. See [the updated docs](/pekdon/pekwm/blob/master/doc/development.md#issue-tracker) on how to enable.

If it doesn't help it should at least provide more information on the issue.

**Comment by biopsin** [comment]
Master test- it would create on first try 255 zombies ; second try 213 ; third try 87 ; forth 54 ; fifth 153 .. but at least on each try they are all killed second after,
so no dangling defuncts now.

Have not gotten around to enable trace loggging, 
sorry no logs for you at the moment..

**Comment by pekdon** [comment]
Do I understand correctly that the processes are joined now but it takes some time or until next child is spawned and finishes?

**Comment by pekdon** [comment]
And also, that is a LOT of processes. But you where saying the events where triggering too much, needs to be looked into as well.

**Comment by biopsin** [comment]
No they are not joined, they get cleaned up in between each try.

**Comment by pekdon** [comment]
@biopsin some refactoring has been done on master related to how move is handled, can very well resolve the issues you are experiencing. Still early on/very untested.

**Comment by biopsin** [comment]
@pekdon I'll take a new swing at it closer or in the weekend

**Comment by pekdon** [comment]
@biopsin, did you get to try it out during the weekend? :)

**Comment by biopsin** [comment]
sorry @pekdon , family stuff got in the way. I'll try in the morning before work.

**Comment by biopsin** [comment]
@pekdon Maybe using wmctrl should be avoided completely, and use those new window scaling option SetGeometry, what do you think?

**Comment by pekdon** [comment]
I think that would be as broken as is today even with the new actions, there's no code handling updated size of the Frame. I will close this issue (zombies are gone) and create a new one trying to describe the issue you are experiencing.
