### ISSUE TITLE
root window unavailable, can't start

### ISSUE THREAD

**Issue by FrnchFrgg** [pekdon/pekwm#40]
Latest master cannot start, giving the error message `pekwm: root window unavailable, can't start`.

A git bisect tells that the commit introducing the bug is 27b5082e11a (Move more resources out of WindowManager)

**Comment by pekdon** [comment]
As this works for me (and verified with a couple of other users) can you tell how you start pekwm, what applications you are running and other environment specifics.

Have you tried start pekwm in Xnest (Xnest :1 ; pekwm --display :1) and see if that works for you?

**Comment by FrnchFrgg** [comment]
I will try tomorrow. Some notes: I did not try a normal launch yet, only a `pekwm --replace`. Maybe that is what broke. There is clearly a change in behaviour at the aforementioned commit.

**Comment by pekdon** [comment]
That explains it, I am able to reproduce here so no need for more details.

**Comment by pekdon** [comment]
Should be working on master now, let me know if it still does not work for you.
