### ISSUE TITLE
Maximizing windows when harbour is hidden does not use up full screen

### ISSUE THREAD

**Issue by pclouds** [pekdon/pekwm#42]
With Harbour/MaximizeOver = False, maximized windows should not overlap harbour area. But when the harbour area is hidden with Windows+H, maximizing windows still uses the same amount of area, leaving one empty black column on the right. Not sure if this is intended behavior.

**Comment by pekdon** [comment]
Found the issue, a regression caused by change of for loop. Fixed it locally but will add a test before pushing the fix.

**Comment by pekdon** [comment]
Should hopefully work as expected for you now, seems to be working fine for me at least.

**Comment by maoamid** [comment]
@pekdon please verify again against latest git (tested today):

- put something in a harbour (tint2 panel for example)
- ctrl+h to be sure it is visible
- maximize any window
=> some windows lock up, I cannot interact with it and looks strange, it seems also to lose focus (Firefox, VSCode) no window resize, after Toggle de maximize all went back normaly
 some windows cannot be maximized at all, only are re-positioned smarter (XTerm)
 some windows are "maximized" with a width out of the current screen size

**Comment by pekdon** [comment]
@maoamid as I'm unfaimliar with tint2 (apart from by name), would you mind sharing how you start it. Didn't see any specifics on how to start it as a dockapp (so that it ends up in the harbour).

Second, how do you maximize (Toggle Maximized True True?)

On XTerm, it honours the resize increments and will not cover the full screen. You can disable that by creating an autoproperty matching the terminal with the following CfgDeny:

```
CfgDeny = "ResizeInc"
```

**Comment by maoamid** [comment]
You are right, I forget about XTerm, my mistake.

Beside that, Tint2 have an option in panel tab from tin2conf tool: "Put panel in a dock". For me it was the fastest way to see the harbour in action (I use a no panel setup and a key that toggle the view of harbour / dock / slit / or even a panel is a nice way to maintain an workspace clean but also usable)

Maximize: 
```DoubleClick = "1" { Actions = "Toggle Maximized True True" }``` in mouse config
```KeyPress = "Mod4 M" { Actions = "Toggle Maximized True True" }``` in keys

**Comment by maoamid** [comment]
Be aware that without the constraints imposed by the autoproperty you mentioned, the xterm window had the same issue like all the others windows when the harbour is visible. (Hope only using the tint2 not to be a specific case exception).
Thank you for looking into it

**Comment by pekdon** [comment]
It seems to be a tint2 specifc misbehaviour, wirks just as expected with lets say wmtime.

Should create a separate issue for the tint2 issues, my first guess is that the width of the dock app cause calculations to be off.

**Comment by maoamid** [comment]
true: if I set the tint2 panel to a fixed width in pixels, the issue is gone (I don't know if all the dockapps have a fixed width).
One question: is a config to make windows maximize on screen independent of the harbour visibility and put the harbour allways on top of window stack?
