### ISSUE TITLE
Feature request: Window Placement: choose head by focused window, not by mouse cursor

### ISSUE THREAD

**Issue by okraits** [pekdon/pekwm#43]
New windows currently are placed on the head where the mouse cursor is.

When using a keyboard centric workflow, it would be better if new windows would be placed on the head where the focused window is.

So I suggest to introduce a config option to change that behaviour. Under the Placement-section something like:

SelectHeadBy (string): MouseCursor | FocusedWindow

**Comment by pekdon** [comment]
Thanks for the request, merged to master now.

**Comment by okraits** [comment]
Thanks for the implementation :)
