### ISSUE TITLE
Feature request: autoproperty to ignore resize hints

### ISSUE THREAD

**Issue by pclouds** [pekdon/pekwm#47]
I have the same problem as described in https://dwm.suckless.org/faq/, "I've got a 1 or 2 pixel gap between the right side of my terminal and the right side of the screen, and I want to turn it off". The terminal in this case is urxvt.

dwm is not the only wm that has this, fluxbox has it too (though I can't remember if I noticed the same problem there). Since ignoring resize hints could be dangerous, this could just be set per window/app, instead of globally like dwm.

**Comment by pekdon** [comment]
I guess a good place to place this would be adding ResizeHint to the CfgDeny autoproperty, you're not the first one not liking this behaviour so I guess it's worth adding.

**Comment by pekdon** [comment]
Should be working in master using:

```
CfgDeny = "ResizeInc"
```

**Comment by pclouds** [comment]
Works like a charm. Thank you!
