### ISSUE TITLE
make sure alt-tab menu is at least wide enough for the title

### ISSUE THREAD

**Issue by pclouds** [pekdon/pekwm#53]
At one point I only have one terminal named "sh", and Alt-Tab menu shows a menu with one item, wide enough for just "sh". The menu title "MRU Windows" is cut down to just "M".

It looks weird, not only because the truncated menu title, but because the menu is so tiny. Perhaps we should keep the width large enough for the window title, or even better, let people set minimum menu width.

**Comment by biopsin** [comment]
Mind share a screenshot, I'm having trouble visiualizing the issue at hand?
Defalt [ALT Tab] in https://github.com/pekdon/pekwm/blob/master/data/keys
is KeyPress = "Mod1 Tab" { Actions = "NextFrame EndRaise" }
what have you assigned this key combination to?

**Comment by pclouds** [comment]
Here is the screenshot https://imgur.com/a/90Hd21L (I started urxvt differently this time so it shows urxvt instead of sh)

	KeyPress = "Mod1 Shift Tab" { Actions = "PrevFrameMRU AlwaysRaise" }

**Comment by biopsin** [comment]
@pclouds confirmed; I see what you mean. 
I use Simple Terminal client and the menu does shrink to what ever title lengt,
in my case just a tilde character.

**Comment by pekdon** [comment]
Now all menu should consider the title size when calculating width. Thanks for reporting the issue and hopefully this works as expected for you now.
