### ISSUE TITLE
Update Keybindings for 0.2.0 release

### ISSUE THREAD

**Issue by pekdon** [pekdon/pekwm#56]
The default keybindings have been around for quite some time and as it has been mentioned in  #52 modernizing the keybindings seems to be a good idea.

In an overhaul I think the following should be addressed:

- Reduce the number of top-level keybindings to reduce the risk of conflicts.
- Consider switching most top-level keybindings to Mod4 or at least a few single Ctrl/Mod1 combination start of chains
- Reduce number of pre-defined applications and/or use a system variable file for TERMINAL, BROWSER etc.

There are probably a lot more to be considered here and I would love to see user suggestions here.

@pclouds, @okraits and @biopsin ... Interested in helping out?

**Comment by pclouds** [comment]
>  Interested in helping out?

oh yeah I migrated from fluxbox (and gnome before that) and the one keybidings I missed was moving a window to left or right half of the screen. I believe MS Windows has this too but I don't use it so I can't say for sure. I added this part in keys and pretty happy with it

```
	# Move (and optionally resize) to Corner
	Chain = "Ctrl Mod1 C" {
		KeyPress = "Mod1 Q" { Actions = "SetGeometry 50%x50%+0+0 CURRENT" }
		KeyPress = "Mod1 W" { Actions = "SetGeometry 100%x50%+0+0 CURRENT" }
		KeyPress = "Mod1 E" { Actions = "SetGeometry 50%x50%+50%+0 CURRENT" }
		KeyPress = "Mod1 A" { Actions = "SetGeometry 50%x100%+0+0 CURRENT" }
		KeyPress = "Mod1 D" { Actions = "SetGeometry 50%x100%+50%+0 CURRENT" }
		KeyPress = "Mod1 Z" { Actions = "SetGeometry 50%x50%+0+50% CURRENT" }
		KeyPress = "Mod1 X" { Actions = "SetGeometry 100%x50%+0+50% CURRENT" }
		KeyPress = "Mod1 C" { Actions = "SetGeometry 50%x50%+50%+50% CURRENT" }
	}
```

**Comment by okraits** [comment]
I can do a PR with notable things I modified/added in the default keys file. Then we can discuss individual parts, ok?

**Comment by okraits** [comment]
I added some comments to #57 to explain what I changed and why.

Additionally I'll add my keys file to show my general work style.


[keys.txt](https://github.com/pekdon/pekwm/files/5936946/keys.txt)

**Comment by pekdon** [comment]
Anything else we should change before a release or should we close this one for now?

**Comment by biopsin** [comment]
Browsed over Blender and Gimp shortkeys and looks good for release on my end at least.

**Comment by pekdon** [comment]
Closing this for now

**Comment by pclouds** [comment]
some more in #64
