### ISSUE TITLE
"NextFrameMRU AlwaysRaise" does not list fullscreen windows

### ISSUE THREAD

**Issue by pclouds** [pekdon/pekwm#58]
Seems weird that fullscreen windows are excluded. This is a linux game, maybe they're doing something wrong with WM hints? It  worked with fluxbox if I remember correctly.

**Comment by pekdon** [comment]
There are quite a few pre-conditions for a window to be included in the list:

- Sticky or on current workspace
- Mapped (not iconified)
- FocusToggle not in Skip (check type rules and auto properties)
- Allowed to give input focus (hint controlled)

Easy way to learn whether or not this is a bug (or unintended or whatnot) is to xprop on the window and paste the output here.

**Comment by pclouds** [comment]
```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE
_PEKWM_FRAME_ID(CARDINAL) = 5
_PEKWM_FRAME_ACTIVE(CARDINAL) = 1
_PEKWM_FRAME_ORDER(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_NAME(UTF8_STRING) = "Invisible, Inc."
WM_NAME(STRING) = "Invisible, Inc."
XdndAware(ATOM) = BITMAP
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 26364
WM_LOCALE_NAME(STRING) = "C"
WM_CLASS(STRING) = "InvisibleInc", "InvisibleInc"
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 0, 0
WM_CLIENT_MACHINE(STRING) = "tro"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0, 0x0, 0x5, 0x438, 0x1, 0x1d84f9d9
STEAM_GAME(CARDINAL) = 243970
```

**Comment by pclouds** [comment]
I added some debug in ActionHandler::createMenuInclude(). Apparently it's frame->isMapped() being false. I guess the game unmaps its window as soon as it loses focus and remaps it back later? By removing isMapped() condition, I can switch back to the game just fine (showing everything it has, so mapped)

Perhaps worth noting that I also use `rofi -show window` and it does show this game (and the reason I could switch back)

**Comment by pclouds** [comment]
BTW how do you convert std::wstring back to std::string (for logging)?

**Comment by pekdon** [comment]
On the logging @pclouds , I think I will just change the ofstream to a wofstream and use wcerr then no conversion is required in the pekwm side.

**Comment by pekdon** [comment]
Thanks for the information, I skipped the mapped check that should be redundant and should get it behave as expected on your setup.

**Comment by pclouds** [comment]
Just a quick note because I have another game that does not show up in alt-tab. Turns out, when it loses focus, it will automatically iconify, and the defaul behavior is not show iconified windows.

We probably don't have to do anything here, but I wonder if it makes more sense to show iconified windows by default. The fact that there's no easy way (that i know of) to list iconified windows might agree with that. This is not a problem with other WMs of course if they have a panel that lists all windows all the time.

The other thought I had was just to mention about this (e.g. games sometimes often do this, beware...) but people probably would not see it anyway.

**Comment by okraits** [comment]
@pclouds You can get a menu of all iconified windows with the action `ShowMenu Icon`.

I would not list iconified windows in alt-tab because iconifying them is a way to get them temporarily out of the way.

**Comment by pclouds** [comment]
But my first problem is I didn't even know that the game iconified itself. I had to add debug code to find that out. For experienced users, perhaps you know to see both menu lists, but that's asking too much for new people.

If iconification is to get out of the way, we could still have the option to sort and put them at the bottom, for example. Or suggest people to change defaults. Defaults should something more friendly.

Or someway to indicate a window is iconified...

**Comment by okraits** [comment]
I just saw that there's a boolean argument for the `NextFrame` family of actions to define if iconified windows should be included in the focus cycle:

https://github.com/pekdon/pekwm/blob/master/doc/actions.md#actions-1

> NextFrameMRU (string boolean)
> If boolean is true, also goes thru iconified windows. Defaults to false.

**Comment by pclouds** [comment]
Yes that's exactly what I did to make it work for me. Though I still think the default (not shown) may need reconsideration. Between the two choices:

* show iconified by default, user annoyed and customizes to hide them
* not show by default, some user with unlucky app wonders "where did my app go?". There's very little clue to go back and unhide them.

**Comment by pekdon** [comment]
As there's no "right" way of doing things here, boiling down to user preference, I think the way forward is:

1. Keep iconified hidden by default
2. Add Entry to the FAQ on Games not included in Windows
3. Make it easier to enable display of iconified windows
4. Implement a pekwm_panel application

On 3, can be done like this

vars file:

```
# Include iconified windows in window listings such as focus toggle menu
OPTION_SHOW_ICONIFIED="False"
```

keys file:
```
Actions = "NextFrameMRU $OPTION_SHOW_ICONIFIED"
```

Could even consider doing an options file included from the default vars that could be controlled by a pekwm_settings application to toggle common settings on and of.

On 4.

Simple panel, using information from the themes to customise rendering with a clock, workspace indicator and client list to start with.

**Comment by pclouds** [comment]
I could at least help with 2.

Another option perhaps is: if pekwm can detect iconification initiated not by itself, and it supports to hook into notification daemon (e.g. running notify-send), then we can have a small popup like "window iconified". This could also be helpful for silent actions such as reload config file (i.e. saying "reloaded" to confirm the action).

**Comment by pclouds** [comment]
For future reference, the "minimize fullscreen window when losing focus" is actually a (default) feature in libsdl.so, widely used in games

https://github.com/libsdl-org/SDL-historical-archive/commit/a8836b0766e000de082c4c946ff700d5ad28bd95
