### ISSUE TITLE
'master' branch is broken

### ISSUE THREAD

**Issue by pclouds** [pekdon/pekwm#59]
start pekwm, alt-tab twice (I use "NextFrameMRU AlwaysRaise") and pekwm crashes. bisect pointed to 4f70c37 (Add ImageMapped texture, map colors in images., 2021-02-09)

**Comment by pekdon** [comment]
Thanks for reporting, will look into it as soon as time permits!

**Comment by pclouds** [comment]
Some data points: switching windows between urxvt and emacs is no problem, but switching firefox (or steam) is. I'm using firefox version 85.0

**Comment by pekdon** [comment]
Thanks for the additional information, it was the icon handling for the clients that was broken and thus only happened when using Firefox or other applications who set _NET_WM_ICON.

Should be working ok on master again.
