### ISSUE TITLE
WidthxHeight reported in pixels for character cell windows.

### ISSUE THREAD

**Issue by caoliver** [pekdon/pekwm#6]
About a week ago, I switched to the master branch from 0.1.17, now when adjusting a fixed width font window, the geometry is reported in pixels rather than character cells.  This is terribly unhelpful if you want to adjust to say 80 columns.  What commit changed this?  How can I reverse it?

**Comment by pekdon** [comment]
The old behavior is reverted on master, update and give it a go!
