### ISSUE TITLE
CurrHeadSelector = "FocusedWindow" conflicts with menu placement

### ISSUE THREAD

**Issue by okraits** [pekdon/pekwm#60]
Environment:

* Dualhead setup
* Using `CurrHeadSelector = "FocusedWindow"`

How to reproduce:

* focused window is on head 2
* mouse cursor is on head 1
* bring up any menu (by clicking on the desktop or by keypress)
* the menu should appear at the cursor position, but instead it appears on head 2 on the edge

**Comment by pekdon** [comment]
Would be neat if you could try that out @okraits as I have no multi-head setup at the moment.

**Comment by pclouds** [comment]
haven't tried this, but @cnasten looks like xephyr supports multi-head setup too

https://blog.sulami.xyz/posts/using-xephyr-to-simulate-multiple-monitors/

**Comment by pekdon** [comment]
@pclouds thanks for reminding me, probably should use something like that for testing!

**Comment by okraits** [comment]
@pekdon Yes, that fixes the issue!

**Comment by pekdon** [comment]
Thanks for the report and fix verification @okraits
