### ISSUE TITLE
Don't hardcode SYSCONFDIR to /usr/etc/pekwm

### ISSUE THREAD

**Issue by biopsin** [pekdon/pekwm#69]
Im strugling overriding to SYSCONFDIR=/etc/pekwm with a doable make_install_args,
for now I just patch both CMakeLists.txt with in a pre_build function
```
	sed 's|${CMAKE_INSTALL_PREFIX}/etc|/etc|' -i CMakeLists.txt
	sed 's| etc| /etc|' -i data/CMakeLists.txt
```
Any ideas how to popper override it without hacking on CMakeLists.txt?

**Comment by pclouds** [comment]
I had this problem the other day with libdir (not this project) this should work, maybe

    cmake -DCMAKE_INSTALL_SYSCONFDIR=/etc 

See https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by biopsin** [comment]
@pclouds tnx for suggestion, but CMAKE_INSTALL_SYSCONFDIR variable is not used in the prosject. 
Guess I should ask the void community what workarounds exist, because I can't get the "obvious ones" to work..hmhmhm

**Comment by pekdon** [comment]
@biopsin I guess updating pekwm to use them would be the "correct" way of fixing this would it not?!

**Comment by pclouds** [comment]
@pekdon allowing customization is definitely the way to go, although I don't think you must include that module.

I have an interest here too because I might provide pekwm ebuild for gentoo (and rather avoid patching if possible), and a quick grep through all gentoo packages shows this. As you see it's not exactly standardized among packages

                -DCMAKE_INSTALL_SYSCONFDIR="${EPREFIX}/etc"
                -DDEFAULT_SYSCONFDIR="${EPREFIX}/etc/mysql"
                -DINSTALL_SYSCONFDIR="${EPREFIX}"/etc
                -DSYSCONFDIR="${EPREFIX}"/etc
                -Dsysconfdir=/etc
                -DSYSCONF_INSTALL_DIR="${EPREFIX}"/etc

**Comment by biopsin** [comment]
@pekdon @pclouds I bow in compliance, unless it's a obvious and easy matter to correct, I would need todo some readup on cmakefiles as it's yet another unfamiliar topic for me.

**Comment by pekdon** [comment]
Any preferences? I think -DSYSCONFDIR is what I would go for, but what seems to be the most common one in the portage tree @pclouds ?

**Comment by pclouds** [comment]
Stats from portage tree here. Note that there's a lot of automation involved and it's probably not entirely accurate

     29 -DSYSCONFDIR
     21 -DCMAKE_INSTALL_SYSCONFDIR
     18 -DSYSCONF_INSTALL_DIR
      3 -DDEFAULT_SYSCONFDIR
      2 -Dsysconfdir
      2 -DINSTALL_SYSCONFDIR

**Comment by pekdon** [comment]
Then SYSCONFDIR it is then. Having issues with the connectivity on my laptop (not at home over the weekend) so feel free to make a PR (can merge with the GitHub app) or I'll have a go at it next week.

**Comment by biopsin** [comment]
I'm doing some testing crudely shoving it in, which works for the main, but variable gets lost for the  data/CMakeList.txt, but so far I'm learning so don't mind beating me to a PR ;)
```
if (SYSCONFDIR)
    set(SYSCONFDIR ${SYSCONFDIR} CACHE PATH "conf dir")
else ()
    set(SYSCONFDIR /etc CACHE PATH "conf dir")
endif ()
```
Have a nice weekend!

**Comment by pclouds** [comment]
And I still hate cmake so it will be a game between you two :)

**Comment by markand** [comment]
One should not create any kind of variable by hand but use the [GNUInstallDirs](https://cmake.org/cmake/help/v3.20/module/GNUInstallDirs.html) module and/or the TYPE argument in [install](https://cmake.org/cmake/help/v3.20/command/install.html#targets) command instead.

**Comment by biopsin** [comment]
@markand Thank you for pointer, I'll redo the PR.

**Comment by biopsin** [comment]
@markand if you like to give some feedback please do, I'm somewhat flying blind here..
https://github.com/pekdon/pekwm/pull/71/commits/c347cef5bc5f47e50a9fd2baa4222baefc0ee0a6

**Comment by markand** [comment]
hi @biopsin, I've added a comment to the PR, otherwise LGTM.
