### ISSUE TITLE
New windows fail to appear on fbpanel taskbar or pager.

### ISSUE THREAD

**Issue by caoliver** [pekdon/pekwm#7]
New windows fail to appear on fbpanel's pager or taskbar until changed or another window is created.  This wasn't the case with 0.1.17.

I've rolled my boxes back to 0.1.17 for now.

**Comment by pekdon** [comment]
Am I getting you right that something along the lines of:

1. Start fbpanel
2. Start xterm
3. Nothing shows on fbpanels pager or taskbar
4. Resize xterm
5. Xterm now shows on fbpanels pager and taskbar

And on 0.1.17 steps 3 and 4 was not there and could be skipped?

**Comment by caoliver** [comment]
On Mon, 14 Dec 2020 22:27:21 -0800
Claes Nästén <notifications@github.com> wrote:

> Am I getting you right that something along the lines of:
> 
> 1. Start fbpanel
> 2. Start xterm
> 3. Nothing shows on fbpanels pager or taskbar
> 4. Resize xterm
> 5. Xterm now shows on fbpanels pager and taskbar
> 
> And on 0.1.17 steps 3 and 4 was not there and could be skipped?

Sort of.  Here is a video link with a simple screen rocorder session showing
the symptoms with a fresh build of pekwm from the master branch.

https://youtu.be/zH70n1Y7YlA

Incidentally, the size display for character cell windows works fine now.
Thanks for the reversion.

If there's anything else I can do to help, don't hesitate to respond.

Sincerely,

-- 
Christopher Oliver <caobizz@gmail.com>

**Comment by pekdon** [comment]
Have a fix in the works, try the branch _update-client-list-7_ if you want to give it a go.

**Comment by pekdon** [comment]
This should be working ok on master now @caoliver, thanks for reporting!

**Comment by caoliver** [comment]
Things seem normal now.  Thanks!

-- 
Christopher Oliver <caobizz@gmail.com>
