### ISSUE TITLE
GotoWorkspace loses focus sometimes when moving to a new workspace

### ISSUE THREAD

**Issue by pclouds** [pekdon/pekwm#75]
I can't reliably reproduce this although this happens often, perhaps I'll need to add more tracing or something. Anyway, I do "GotoWorkspace Right" twice to move the current window two workspaces to the right, but sometimes after moving by one workspace, the current window does not have focus anymore, so another window is being moved the second time.

Hmm.. this seems reliable so far:

- switch to the second workspace first (no moving windows), keep one window focused there
- switch back to the first workspace, select your favourite window
- now move it to the second workspace, focus is lost

**Comment by pclouds** [comment]
The problem seems to be "Ctrl Mod1 Shift Left" is a combination of two actions "SendToWorkspace Left; GoToWorkspace Left " which does not do anything about window focus. Is it acceptable to have an option in SendToWorkspace to "send and remain focused in that workspace"?

**Comment by pekdon** [comment]
It sure is even though it might look a bit weird saying a client is focused but on another Workspace.

Unfortunately the word active is already used for the active client in a frame so not sure if there's a less confusing word to use than focused?
