### ISSUE TITLE
Icon AutoProperty

### ISSUE THREAD

**Issue by pekdon** [pekdon/pekwm#78]
Not all applications set _NET_WM_ICON on themselves, which make for a lack-luster appearance in panels and pekwm menus.

Create a Icon auto property that will set the _NET_WM_ICON on matching clients, icons will be loaded from the standard Icon path:

```
Files {
    Icons = "/path/to/icons"
}
```

Property would look like this:

```
Property = "^xterm,^XTerm" {
    Icon = "term.png" # any texture would work, fixed image is default
}
```

**Comment by pclouds** [comment]
GNOME (and probably KDE) too also does something to use larger icons (and I don't think they can just set `_NET_WM_ICON` for that). If possible, an semi-automated way to pick up larger icons would be nice.

**Comment by pekdon** [comment]
@pclouds the hint allows for providing a list of icons, typically used to provide multiple sizes. The spec does not enforce any specific size to be used so the user can set a larger icon if they want to.
