### ISSUE TITLE
Oficial pekwm repository and new release

### ISSUE THREAD

**Issue by charles2910** [pekdon/pekwm#8]
Hi.

I'd like to know if this is an oficial pekwm repo since in pekwm.org there is no mention of it. I'm asking because of debian packaging. 

It's currently out of debian testing archive (i.e. it's not going into the debian stable) and I was looking into it to release a new debian package version (0.1.17-4) fixing the bug preventing it to build with gcc 10 and put the packging up to date with modern standards.

If this is a sort of oficial git repo, we could set it as the upstream source for the debian package because I've seen a lot of commits since version 0.1.17. Also it would be really cool if you could release a new upstream version (perhaps 0.1.18). This would facilitate a lot the packging.

Thanks,
Charles

**Comment by pekdon** [comment]
Hi,

This is indeed the official pekwm repository. The pekwm.org domain has been taken over by I don't know how for whatever purpose I don't really understand.

pekwm.org (and also related pekdon.net) domains are no longer what they used to be after they expired.

And yeah, might just go ahead and release the current state as 0.1.18 as it is at least in better shape than 0.1.17.

/Claes
