### ISSUE TITLE
[panel] Generalize WorkspaceNumber widget

### ISSUE THREAD

**Issue by okraits** [pekdon/pekwm#87]
The WorkspaceNumber widget displays the number of the currently focused workspace.

Another possibility would be to show the name of the current workspace, either with a separate widget or with the WorkspaceNumber and a configuration option.

**Comment by pekdon** [comment]
Another option, would be a Text widget that has some sort of format string that can take include workspace number, name, active client etc.

**Comment by pekdon** [comment]
I'll go for introducing a Text widget, should be the most flexible and avoid inflation of specific types of widgets.

**Comment by okraits** [comment]
Or if the widget would display the workspace name, then it would be up to the user how to name and thus display the workspaces.

**Comment by pekdon** [comment]
Closing this, the new Text widget should be general enough to solve this.

**Comment by okraits** [comment]
Thank you!
