### ISSUE TITLE
[panel] Add an option to choose the head(s) where the panel should be displayed

### ISSUE THREAD

**Issue by okraits** [pekdon/pekwm#88]
Currently the panel stretches across all active heads. An option to select one or several heads to display the panel on would be useful.

**Comment by pekdon** [comment]
If multiple heads, should the panel repeat (would be tricky with a systray in the future) itself or stretch?

**Comment by pclouds** [comment]
Another option is simply move the panel to where the focus is (or where the mouse is, depending on preference)

**Comment by okraits** [comment]
> If multiple heads, should the panel repeat (would be tricky with a systray in the future) itself or stretch?

The simple solution (apart from the systray) would be to mirror the panel to all heads. For a panel stretching across all heads, it would take more effort to calculate the width of the items of the client list if an item should not go across the head edge.
